services:
  backend:
    build: ./pdf-tool-backend   # <â€” FIXED: backend is now a mapping
    container_name: pdf-tool-backend
    ports:
      - "8001:8000"
    volumes:
      - ./pdf-tool-backend:/app
    # environment:
    #   - ALLOWED_ORIGINS=http://localhost:5173

